name: WorkSpace
run-name: ${{ github.actor }} workspace
on: workflow_dispatch
permissions:
  repository-projects: write
  contents: write
jobs:
  vs-code-server:
    runs-on: ubuntu-latest
    steps:
      - run: curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
      - run: tar -xf vscode_cli.tar.gz
      - run: rm ./vscode_cli.tar.gz
      - run: sudo mv ./code /usr/local/bin/code-cli
      - run: sudo apt update && sudo apt upgrade -y
      - run: sudo apt install --fix-missing language-pack-ja
      - run: sudo update-locale LANG=ja_JP.UTF-8 && locale
      - run: sudo timedatectl set-timezone Asia/Tokyo
      - run: sudo apt install --fix-missing manpages-ja manpages-ja-dev
      - run: code-cli tunnel --accept-server-license-terms --name the-inf_workspace
