name: vscodeserver
run-name: ${{ github.actor }}
on: [push]
jobs:
  vs-code-server:
    runs-on: windows-latest
    steps:
      - run: curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
      - run: tar -xf vscode_cli.tar.gz
      - run: ./code tunnel --name the-infinitys_tunnel
